scripts/hello_world_RishabhKemni.go
First PR for #Hacktoberfest 2022
Please merge @fineanmol
=> Golang hello world

CONTRIBUTORS.md, profiles/aditya_more.md, scripts/hello_world_AdityaMore7000.py
Hello @fineanmol, I have added my name in Contributors.md, please kindly accept it and give the Hacktober accepted tag
=> updated contributors.md with my name

CONTRIBUTORS.md, profiles/Heru_Hermawan.md, scripts/hello_world_heruhermawan.js
this is my contribution to HF2022
=> my contribution to HF2022

CONTRIBUTORS.md, profiles/bagusok.md, scripts/hello_world_bagusok.js
=> Add Contribution and Script

scripts/InnocentDaksh63.java
i have merges the hello world script in java at your repository
=> InnocentDaksh63.java

CONTRIBUTORS.md, profiles/hardik_pratap_singh.md, scripts/hello_world_hardik.py
I have added all the 3 tasks as was suggested and informed by you.
Kindly merge my pr.
thanks
=> added hardik info

scripts/fetch-result-script.py
Pre-requisite: You should know how to get endpoint using either BurpSuit or Postman, etc.
=> Script to Fetch University results

CONTRIBUTORS.md, profiles/Abhay Raj.md, scripts/hello_world_abhay_raj.py
Added my profile and add name in contributors list for pull request (Hacktoberfest 2022)
=> hacktoberfest 2022

CONTRIBUTORS.md, profiles/Renzo_Cabarios.md, scripts/hello_world_renzo.ts
- Add Renzo Cabarios in readme
- Add Renzo Cabarios readme
- Add hello_world-renzo.ts
=> Renzo Cabarios Contribution

CONTRIBUTORS.md, profiles/sambhav.md, scripts/hello_world_Sambhav.sh
=> add bash script

scripts/Facto.py
#hacktoberfest #hacktoberfest-accepted #contribute #open-source #hacktoberfest2022
=> Initail Commit

CONTRIBUTORS.md, profiles/Sooraj_Kr.md, scripts/hola_world_sks2002.go
=> Sooraj Kumar S

CONTRIBUTORS.md, profiles/Zuzexx.md, scripts/hello_world_zuzexx.php
added my_name.md, hello world script in PHP and my information to CONTRIBUTORS.md
=> added my tasks

CONTRIBUTORS.md
=> update - from Aastha

CONTRIBUTORS.md, profiles/Sahitya.md, scripts/hello_world_Sahitya.py
I am waiting for my 1st PR in 2022
=> added my profile details under hacktoberfest 2022

CONTRIBUTORS.md, profiles/SamirKaushik.md, scripts/helloworld.kt
I've completed all 3 steps for contributing to this repository. Kindly consider merging the changes.
=> Hacktoberfest PR

RatMazeBacktracking.cpp
RatMazeBacktracking code with Efficient Approach and Better Time and Space Complexity
=> RatMazeBacktracking code with Efficient Approach

README.md
I had elaborated very well about Hacktoberfest and open source unlike previous one.
Addresses #<3>
=> added more details in the starting paras .

CONTRIBUTORS.md, profiles/Ian Kisali.md, scripts/hello_world_iankisali.c
I added my profile and a hello world script
=> added my profile and created a C file

scripts/pyramid_pattern_malyabansalper.js
I have added a pattern program following the convention and best practices as per the repository. Kindly merge the PR.
=> Pyramid Pattern HacktoberFest2022

profiles/Rahul6918.md
My previous pr is not showing that's why I have to do it again
=> Updated my profile page

profiles/MuhammadNoorani.md, readme.md
Mark it as Hacktoberfest/Hacktoberfest-accepted
=> Added Profile

README.md, scripts/Welcome_to_Programming_MuhammadNoorani.c
Mark it as Hacktoberfest Accepted
=> Added Script - C Language

hello_world_happyhearthacker.py
Created a new file to improve the repository. Hoping you will accept my PR.
=> hello_world_happyhearthacker.py

scripts/Dijkstra’s shortest path algorithm by Suraj.cpp
It's Fun and Easy to Understand.
Please Merge this PR.
=> Here's a Dijsktra Algorithm Program

scripts/hello_world_Yash_Srivastav.cpp
3rd and Final Task as mentioned on contributing guide...
=> Create hello_world_Yash_Srivastav.cpp  THANK YOU!!!

scripts/password checker.py
This will let a particular string to be checked to see if its a strong password or not!
=> Created password checker.py

login project/Readme.md, login project/index.html, login project/style.css
This is a responsive type of login page best responsive for the phone as well as desktop views.
=> Adding Front-end login page project

scripts/password_checker.py
This will help us know if the string is unto the best security standards or not
=> Added password checker to the repo

CONTRIBUTORS.md, profiles/Nandini_Gangadharan.md
Added my name to the Contributors file and made a profile page.
=> New contributor

M_Color_Backtracking.cpp
M_Color_Backtracking.cpp problem in efficient way!
Starred your repo!
Do give hacktoberfest-accepted label!
=> M_Color_Backtracking.cpp

scripts/hello_world_shrey0902.cpp
=> Added my hello world script 

CONTRIBUTORS.md, scripts/hello_world_nishantraghuvanshi.py
-Added my name to the Contributors.md file.
-Added python hello world script.
=> Contributors.md edited and python script added

CONTRIBUTORS.md, profiles/Dev_Kumar_Gupta.md
Hey, I have added the profiles !
Please merge the pr with the hacktoberfest accepted label.
Thanks.
=> Contributed to Profiles

CONTRIBUTORS.md, profiles/Abhishek_Gaurav.md, scripts/main.swift
Hey there, I have followed the same instructions as per your description. I have done the following:
- Added my name in the Contributors.md file
- Added my profile in the profile folder
- Created a simple Hello World code in Swift language, as it wasn't available in Swift so far.
**Thank You**
=> Gauravabhishek4u

CONTRIBUTORS.md, profiles/Kush_Munot.md, scripts/Kush.java
Hello I have merged and created my first PR. Thanks !!
=> Added some data and updated the Profiles, Scripts, and Contributors.md

CONTRIBUTORS.md, scripts/Hello_khushi.cpp
I have updated contributors.md and script files.
please assign hacktoberfest labels.
=> Updated 2 files

scripts/split_excel_file.py
I have added my name to **Contributor.md** and added a script that can split the excel sheets using Python. Please merge my pull request and assign a `hacktoberfest accepted` label.
=> Split Excel Sheets - Python

CONTRIBUTORS.md, profiles/Tyler_Bacon.md, scripts/hello_world_tbacon781.js
Added a hello world js script. Also added to the contributeors/about me section
=> added to scripts and about me.

CONTRIBUTORS.md
I would love to add my name to the list of contributors!
=> Add Craig WIldhaber to CONTRIBUTORS.md

CONTRIBUTORS.md, scripts/hassanHelloWorld.py
Please Accept my contribution!!! thanks.
=> Hassan's Contribution

CONTRIBUTORS.md, README.md, profiles/agusardi.md, scripts/agusardi.py
I already adding contributors.md,
creating profile.md,
and creating simple hello world script using my chosen programming language, thank you.
=> Completed Doing All Task

CONTRIBUTORS.md, profiles/Dhruv.md, scripts/Dhruv_Helloworld.c
I have done all the tasks which are mentioned. Kindly review it and accept my PR
=> Done all the Task

CONTRIBUTORS.md, profiles/Dennis_Jojo_Kuriakose.md, scripts/Factorial_atmozki.c
=> hacktober noob

CONTRIBUTORS.md, HelloWorld.cpp
=> Contributor added, and Hello World (:

CONTRIBUTORS.md, profiles/Kunal_Kaushik.md, scripts/Hello_World_Kunal.cpp
I added contributors.md,
created profile.md,
and created simple hello world script using my chosen programming language, thank you.
=> Completed_all_tasks

C++ Programs/MaxDifferenceInArray.cpp
This is my PR for Hacktoberfest 2022
=> Added MaxDifferenceInArray.cpp

CONTRIBUTORS.md, profiles/Soustab_Haldar.md, scripts/hello_world_soustab10.go
I have already starred the repository, please merge the PR :)
=> Added all files

1079. Letter Tile Possibilities.txt, 113. Path Sum II.txt, 1137. N-th Tribonacci Number.txt, 118. Pascal's Triangle.txt, 121. Best Time to Buy and Sell Stock.txt, 1286. Iterator for Combination.txt, 1646. Get Maximum in Generated Array.txt, 1863. Sum of All Subset XOR Totals.txt, 2044. Count Number of Maximum Bitwise-OR Subsets.txt, 216. Combination Sum III.txt, 257. Binary Tree Paths.txt, 338. Counting Bits.txt, 39. Combination Sum.txt, 392. Is Subsequence.txt, 4. Median of Two Sorted Arrays.txt, 46. Permutations.txt, 509. Fibonacci Number.txt, 55. Jump Game.txt, 70. Climbing Stairs.txt, 746. Min Cost Climbing Stairs.txt, 77. Combinations.txt, 78. Subsets.txt, 784. Letter Case Permutation.txt, 797. All Paths From Source to Target.txt, 90. Subsets II.txt
This is my first time in Hacktober fest. I contibuted some solutions for LeetCode problems. The code is in Java Language along with link to the Question.
=> competitive Programming code in java

CONTRIBUTORS.md, ChromeExtension Development/StayMotivated/manifest.json, ChromeExtension Development/StayMotivated/popup.html, ChromeExtension Development/StayMotivated/script.js, ChromeExtension Development/StayMotivated/style.css
Stay Motivated chrome extension is added in the chrome extension development folder
Kindly review it and merge this PR under hacktoberfest-accepted label
=> My Contribution- StayMotivated

C++ Programs/linkedlist.cpp
Hello @fineanmol, I have added a problem related to Linked List, which will return the sum of the node range given in the problem statement.
Please do consider the problem and accept the PR request by adding “HACKTOBERFEST-ACCEPTED” label.
Thanks in advance.  😊
https://github.com/seemaPatl
=> Linked List problem

CONTRIBUTORS.md
=> added a bio about nurkholiq

CONTRIBUTORS.md, profiles/Saugat_Rimal.md, scripts/hello_world_saugatrimal.js
All the tasks are completed. Please assign this issue to me under hacktoberfest 2022 and help me in starting my first contribution. I have already starred the repo and forked it.
=> HacktoberFest first contribution

CONTRIBUTORS.md, profiles/Chayandev.md, scripts/Chayandev_HelloWorld.kotlin
Please add those Changes and new files I created.
=> Create Chayandev.md and Chayandev_HelloWorld.kotlin and profile.

profiles/Tanay Dwivedi
=> Create Tanay Dwivedi

C++ Programs/Letter Combinations of a Phone Number.cpp
Given a string containing digits from 2-9 inclusive, return all possible letter combinations that the number could represent. Return the answer in any order.
A mapping of digits to letters (just like on the telephone buttons) is given below. Note that 1 does not map to any letters.
=> Create Letter Combinations of a Phone Number.cpp

Banking System App
Done with adding name to Contributor.md file, added file to profile folder, added a Banking System app in java
=> Create Banking System App

C++ Programs/Quick Sort
=> Create Quick Sort

scripts/hello_world_akshaaatt.rb
Hello world program in Ruby language.
=> Ruby program for Hello world

C++ Programs/Library.cpp
Library Management System is a C++ program that uses File Management to store all data in a.txt file. Users can add, modify, and delete book(s) and student(s) information, as well as assign books to students.
=> Created/Added Library.cpp

profiles/Meekun.md
I created a new file (Meekun.md) in `profiles` directory.
Participation in open source contribution and hacktoberfest.
=> Add a profile page to the profiles directory

scripts/NftMinter.sol
You doing work bro keep it up👍
=> Created A Nft Minter for anmol bhai

scripts/NftMinter.sol
=> A NFT Minter for anmol bhai

JAVA Programs/Kids_With_the_Greatest_Number_of_Candies.java, JAVA Programs/Matrix_Diagonal_Sum.java
=> adding some java programs

WebsiteVisitor.py
Visit any website n number of times with just few lines of code.
=> WebsiteVisitor.py

BasicToAdvancePatterns_JAVA.java
Majority Patterns from basic to advance in Java.
=> BasicToAdvancePatterns_JAVA.java

scripts/CountPairsWithGivenSum.java
[HacktoberFest 2022] The idea of the code is to find the total number of airs that sum up to a given number. Have also mentioned the time/space complexities and problem description in the code.
=> Counting total no. of pairs with a given sum

C++ Programs/BFS and DFS/BFS_DFS.cpp, C++ Programs/BFS and DFS/queue.h
=> BFS and DFS are added in c++ folder

red heart.py
a beautiful python program for isuue no. 88
=> Create red heart.py

profiles/ManusGupta.md
=> ManusGupta.md

C++ Programs/Palindrome Linked List
Created Palindrome Linked List
=> Create Palindrome Linked List

Fibonacci.java
Added the code of Fibonacci program in Java language.
=> Added Fibonacci Program

reverse_k_node_linked_list.cpp
adding reverse k nodes of the linked list problem
=> adding reverse k nodes of the linked list problem

C++ Programs/constructATree.cpp, C++ Programs/heapImplementation.cpp, C++ Programs/heightDiametreOfATree.cpp, C++ Programs/kthMinElementInArray.cpp, C++ Programs/morrisTraversal.cpp
I have added some Most important questions of leetcode and also important implementations of tress and heaps. Please add hacktoberFest label to it.
=>  added some concepts of programming

CONTRIBUTORS.md
=> Made changes to contributers.md

C++ Programs/INFIXPOST.cpp, C++ Programs/Insertion_sort_using_linked_list.cpp, C++ Programs/Linear_Search.cpp, C++ Programs/ParanthesisChecker.cpp, C++ Programs/factorial.cpp
- factorial.cpp
- INFIXPOST
- insertion_sort_using_linked_list
- Linear_Search
- ParanthesisChecker
=> added 5 programs in C++ progrms folder

C++ Programs/WildCard_Matching.c++
=> WildCart Matching Problem

CPP/BFS/BFS for graph traversal.cpp, README.md
@fineanmol Addresses #324 , Created program for BFS in CPP
=> Addresses #324

C++ Programs/print_2d_array_in_wave_form.cpp, profiles/sudhanshu_purohit.md, scripts/sudhanshuHelloWorld.cpp
hi, I am sudhanshu purohit. I made a program to print 2d array in wave form.
=> cpp program to print an 2d array in wave form

C++ Programs/MergeSort.cpp
This is a merge sort code in C++, kindly consider the pull request.
=> Merge Sort Code Written in C++

profiles/Anish-Parkhi.md
I am a 2022 HactoberFest Contributor
I added my profile in this repo
Thanks for this repo
=> I added my profile

CONTRIBUTORS.md, profiles/stephen-nwankwo.md, scripts/hello_world-stenwire.sh
I added:
- Hello world task
- Readme task
- Profile task
=> stenwire contributions

CONTRIBUTORS.md, profiles/Cesar_Infante.md, scripts/Hello_World_Ceez.js
Thank you for taking a look at my pull request, simple contribution to the CONTRIBUTORS.md file.
=> adding my info to the contribution list

scripts/hello-world_Jonathan-Meza.js
Hi this is my contribution in the folder scripts. Thank you so much
=> contributed script

scripts/conditional_prob_Lorenzobattistela.py
Creation of a conditional probability example python script, to show how cond prob works.
=> Conditional Probability Example - Lorenzobattistela

profiles/Akshat_Agarwal.md, scripts/hello_word_akshat_agarwal.js
Please add my file to your repository with the label hacktoberfest.
=> Hacktoberfest-2022

scripts/Age Calculator
The program takes your age as input and tell you in how many years will you be 100 years old
=> Create Age Calculator

scripts/hello_world_Anurag-Nayak.cpp
Added the cpp code in script folder.
=> Added the cpp code

profiles/Prapul Muttineni
=> Create Prapul Muttineni

scripts/hello_world_notafurryqwq.rb
=> Ruby. First commit.

CONTRIBUTORS.md
=> thanks for the hacktoberfest help!

CONTRIBUTORS.md, scripts/hello_world.py
=> HACKTOBERFEST

CONTRIBUTING.md
-contribution page 
-Added name to the contribution page
-  `1.`
-  `..`
=> task 1 completed

profiles/SandipSapkota9844.md, scripts/hello_world_SandipSapkota9844.js
=> 'SandipSapkota9844_Hacktoberfest'

CONTRIBUTING.md, profiles/AnkitKumar.md
-to learn about open source
-Github is great platform for this
-  `1.` Hello World program initiated
=> first contribution

CONTRIBUTING.md, profiles/vivek.md
=> Added Vivek profile

CONTRIBUTING.md, profiles/Amogh_Patel.md, scripts/hello_world_Amogh.c
-
- 
-  `1.`added profile and hello world program
-  `..`
=> added profile and hello world program

scripts/hello_world_gsinghly.py
=> add hello world python

CONTRIBUTING.md, scripts/Hello_World_kzaildar26.cpp
=> hello world cpp

scripts/Hello_World_Aviace.py
- To  Create a "Hello World" script in any language
- Created above script in in python.
-  `1.` Added code line Print("Hello World")
=> Created Hello world script

profiles/Akarshit7.md, scripts/hello_world_Akarshit7.cpp
=> Added a hello world script

CONTRIBUTING.md, profiles/Ashish.md, scripts/hello_world_ashish3121990.java
=> Contribution from Ashish for hacktoberfest2022

CONTRIBUTING.md, profiles/Mansi_Yeole.md, scripts/hello_world_mansi.cpp
hey , i have made all the changes required for the contribution.
-
-
-  `1.`
-  `..`
=> contributed

CONTRIBUTING.md, profiles/Pradhyum.md
=> add name to contributers list and add profiles page

CONTRIBUTING.md, profiles/Guruvignesh.md, scripts/hello_world_guruvignesh.js
-I am new to contributing opensource project. So, I have some misunderstanding about open source projects.
-For, resolving misunderstanding the about open source projects. So, I make the changes on the profile page and contributing pages on the code. Kindly review and merge my changes.
-  `1.`Add the contributor name and merge the pull requests
=> profile page changes and contributing markdown file changes

CONTRIBUTING.md, profiles/ShrutiLicensed.md
=> added a profile and modified contributors.md

CONTRIBUTING.md
Signed-off-by: Aditya Mathur <61025539+AdityaMathur25@users.noreply.github.com>
-
-
-  `1.`
-  `..`
=> Added My Details In contributers.md

CONTRIBUTING.md, profiles/Prasad_Poojary.md, scripts/hello_world_prasadpoojary.java
=> added my hello world in JAVA

CONTRIBUTING.md, scripts/Snakegame.py
=> Added snake game in python

CONTRIBUTING.md, profiles/Raghav.md, scripts/hello_world_raghav_jha.js
-
-
-  `1. Added Profile Page `
- `2. Create HelloWorld js file `
=> Jha Raghav

scripts/hello_world_SomshuvraBasu.js
- First PR for hacktoberfest
- Hello World Script in JavaScript by user SomshuvraBasu
=> Added Hello World in JS by SomshuvraBasu

CONTRIBUTING.md, profiles/Priyanshu.md, scripts/hello_world_priyanshu68.java
- PR for Hacktoberfest
- Added Required Details
=> Added Required Details

.github/workflows/auto-comment.yml
=> Added hello_world_kbhavre.py to script folder

CONTRIBUTING.md, profiles/Nayaneeka.md, scripts/hello_world_nexi9.java
- PR for Hacktoberfest
- Added required details
=> PR for hacktoberfest

scripts/hello_world_gamercreator1.js
=> Added my version of Hello World

CONTRIBUTING.md, profiles/Kewpie134134.md, scripts/hello_world_kewpie134134.js
=> Hactoberfest2022 new branch

profiles/divyanshu.md, scripts/simplewindow_divyanshu.cpp
Added windows - Getting started with graphics
=> Windows in cpp

CONTRIBUTING.md
- ADD YOUR NAME 
-ADDED CREDENTIALS 
-  `1.`
-  `..`#### Name: [Harshit Sharma ](https://github.com/HARSHITSHARMA18)
- Place: Delhi, Delhi, India
- Bio: A Passionate Developer and Designer pursuing undergrad from Delhi Technological University
- GitHub: [HARSHITSHARMA18](https://github.com/HARSHITSHARMA18)
=> Branch name

CONTRIBUTING.md, profiles/AryanSahoo.md, scripts/HelloWorld_Encyption.cpp
-
-
-  `1.`Updated Contribution.md
-  `2.`Created HelloWorld_Encyption
-  `3.`Updated profile.md
=> Done all three tasks !

scripts/hello_world_chi.sh
- Current existed bash lang hello world is not that interesting.
- A base64 encrpy and decrpt way may be more interesting.
- add scipts/hello_world_chi.sh
=> add hello_world_chi.sh in a fun way

CONTRIBUTING.md
i added my bio in the contribute .md file, please merge
=> Nitin added his bio

CONTRIBUTING.md
Modified the CONTRIBUTING.md file and Added my name to the contributing list.
=> modified Contributing.md and Added my name in contributing list

CONTRIBUTING.md, profiles/Dileep_K_A.md, scripts/hello_world_Dileep2608.py
-
-
-  `1.`Updated [CONTRIBUTING.md](https://github.com/fineanmol/hacktoberfest/blob/master/CONTRIBUTING.md).
-  `2.`Updated profiles directory.
-  `3.`Added a creative hello_world python script.
=> Added creative hello_world script, updated contributing.md, updated profiles directory

CONTRIBUTING.md, scripts/hello_world_jotiraditya.js
=> added the name and hello_world_jotiraditya.js

Rock_Paper_Scissor/app.js, Rock_Paper_Scissor/index.html
=> Rock Paper Scissors

CONTRIBUTING.md
=> Name is added

CONTRIBUTING.md
Added my details from line 1 to line 5
-
-
-  `1.`
-  `..`
added my details for task 1 from line 1 to line 5 for Hacktober fest
=> Updating Contribution for Hacktober with my Detail

CONTRIBUTING.md, profiles/Awosise_Oluwaseun.md, scripts/hello_world_Awosise_Oluwaseun.js
=> Awosise Oluwaseun

CONTRIBUTING.md, profiles/mahika_sharma.md, scripts/HelloWorld.cpp
- contributing.md and profile 
- added myself to contributing.md and profile
- added myself to contributing.md and profile
=> hacktoberfest contribution 

CONTRIBUTING.md, profiles/vaibhav-87.md, scripts/Hello_Word.cpp
=> Tasks Completed

CONTRIBUTING.md, profiles/Amit-Das.md, scripts/Hello_World_das-amit.bhai
-Added the name in CONTRIBUTING.md
-Added the profile in the _profiles_ file
-Added script in BhaiLang language
=> Commited Profile, Script and Updated CONTRIBUTING.md

CONTRIBUTING.md, profiles/Hafizur_Rahman.md, scripts/script_hafeez.js
=> Hafeez profile add

CONTRIBUTING.md, scripts/hello_world_vanam30.py
=> Modified CONTRIBUTING.md and added script file

profiles/Tanuj_Kalonia.md, scripts/hello_world_Tanuj_Kalonia.cpp
=> Added Name, profile page and script 

profiles/Abhishek_Dhiman.md
=> added profile - hacktoberfest

scripts/hello_world_architsharma.js
#Problem
-Create a Hello world project 
-Created a hello world project using javascript
-  Used js to create my hello world project
-  `..`
=> Hello world by archit

CONTRIBUTING.md, profiles/codedhola.md, scripts/helllo_world_codedhola.go, scripts/hello_world_codehola
- was not in the list of contributors
- included myself to the list of contributors 
-  `1.`  Added to to the Contributors.md file
-  `2.` Created a file in profile and added codehola.md as a contributo
-  `3.` Created a file in script and added hello_world_codedhola.go as an hello world program
=> Refactor: added coded-hola as a contributor

CONTRIBUTING.md
=> added name and details

CONTRIBUTING.md, scripts/hello_world_taylor-g592.kt
=> Added megan-taylor to Contributors list

scripts/handtracker.ipynb
-Addition of machine learning project
-Added machine learning project
-  `1.`
-  `..`
=> handtracker using mediapipe

scripts/hello_world_Arith.js
- Program in Scripts Directory
- Added Hello World Program
-  console.log("Hello World") added to Scripts folder.
=> Added Hello World Program

CONTRIBUTING.md, profiles/Fikri_Khairul_Shaleh.md, scripts/hello_world_fikriks.js
=> add: fikriks :rocket:

scripts/avi.py
missing python
added my first python solution
-  `1.`
-  `..`
=> completed my first pull request

CONTRIBUTING.md, profiles/Vivian_Cao.md, scripts/hello_world_caoviv.js
-  Add my name to the CONTRIBUTORS.md file
- Add a Vivian_Cao.md file to the profiles directory
- Add a hello_world_caoviv.js script to the scripts directory
please add the #hacktoberfest-accepted tag <3
=> add name to contributors.md, new profile.md & Hello, World! Script

profiles/Sarah_Esbie.md
Added my profile sarah_esbie.md to the profiles folder.
please add #hacktoberfest-accepted  <3 
#51
=> Added my profile sarah_esbie.md to the profiles folder

profiles/Max_Muller.md, scripts/hello_world_MMVonnSeek.py
=> My contribution

CONTRIBUTING.md, profiles/Temitope.md, scripts/hello_world_temitope.js
- 
- Added my details
-  `1.`
-  `..`
=> Added a new contribution

CONTRIBUTING.md, profiles/gajanan.md
=> added profile md file

CONTRIBUTING.md
=> Added my name in CONTRIBUTING.md

profiles/Webcoderspeed.md
- Add a profile page
- First go to profile dictionary then create a markdown file and fill the infomation mentioned in repo
=> Webcoderspeed profile

scripts/Hello_World_Aaryan376.cpp
-
-
-  `1. Added Hello World Script in Cpp by Aaryan376`
-  `..`
=> Added Hello World Script in Cpp by Aaryan376

CONTRIBUTING.md, profiles/Arjun_Prajapati.md, scripts/hello_world_arjunprajapati.js
=> Completed all the Task

CONTRIBUTING.md, profiles/Aditya_D.md, scripts/Hello_world_Adi271001_AdityaD.py
=> update Aditya_D CONTRIBUTORS.MD 

README.md
=> Added contribution reffrence text Info inside readme

CONTRIBUTING.md, profiles/Tamil_bharathi.md, scripts/Hello_world.c
- Add name in CONTRIBUTING.md file, update profile directory and add hello world program in script directory
- completed all the three tasks.
-> the updated changes were list below in my branch
-> issue fixed #714
=> Tamil code patch 2

CONTRIBUTING.md
Submitting PR for the Hactoberfest. I have starred the repo. 
Added my name to the CONTRIBUTERS.md
=> added myself to the contributers.md

CONTRIBUTING.md, profiles/Tanmay_Roy.md, scripts/HELLO_WORLD_Tanmay.c
Added my profile in profiles.
Added Hello World script.
Added name in CONTRIBUTING.md
=> Pull Request for Hacktoberfest

scripts/helloworld_notcostheta.py
Created helloworld_notcostheta.py
=> Created the helloworld script.

CONTRIBUTING.md, profiles/yash_soni9000.md, scripts/Hello_World_soniyash9000.cpp
- Added more scripts
- synced properly
-  `1.`
-  `..`
=> Added files in scripts,profiles and contribution

CONTRIBUTING.md
-commit
-Stackover flow
-  `1.`
-  `..`
- Added Contribution list
- Added Profile
=> Commit first

CONTRIBUTING.md, profiles/Madhumitha_R.md, scripts/hello_world_Madhumitha.cpp
Completed all the tasks as mentioned in the ReadMe.md file and have added a hello world script in C++, as part of Hacktoberfest 2022
=> Completed all the tasks

countdown/index.html, countdown/script.js, countdown/style.css, scripts/hello_world.java
- creating countdown timer using javascript
- created the countdown time using javascript
-  contains all the functionality
-  start button , stop button, restart button
- time stamp will be shown when the use stop the timer
=> Countdown timer using javascript.

scripts/kunal.cpp
=> created kunal.cpp

CONTRIBUTING.md, profiles/Prahen.md
=> added my profile

CONTRIBUTING.md
- Add contributor to contributing.md
- Added name to contributing.md
=> Add contributor

CONTRIBUTING.md, profiles/Akash_Gautam.md, scripts/Hello_World_Geekblower.cpp
=> Completed all suggested tasks

scripts/hello_world_rahul.cpp
C++ program to print hello world
-
-
-  `1.`
-  `..`
=> hello_world_rahul.cpp

scripts/sorting_of_array.js
JS program to sort the elements of an array.
-
-
-  `1.`
-  `..`
=> sorting_of_array.js

profiles/Harsh.md, scripts/hello_world_Harsh.c++
=> Hello World

scripts/hello_world_m3g4n127001.cs
=> added c# hello world code under scripts

CONTRIBUTING.md, profiles/Shrishail_patil.md, scripts/Hello_World_shrishail356.java
=> Contributed all three tasks 

Armstrong Number Program In Python
=> Create Armstrong Number Program In Python

CONTRIBUTING.md
=> Added Harsh-0986

CONTRIBUTING.md, profiles/lakshay_chuahan.md, scripts/hello_world_lakshay.js
=> Lakshay Chauhan Commit

CONTRIBUTING.md, profiles/RajIshu.md, scripts/HelloWorld-RajIshu.java, scripts/hello_world_RajIshu.java
-  `1.` Added my name to contributing.md 
-  `2.` Added my profile to the profile directory in markdown format
-  `3.` Added my "Hello, world" script file in the script directory in the Java language
-  `4.` Corrected a typo made by a contributor in which I changed 'GitHib' to 'GitHub'
=> Update Contributing.md, profile and script directory

CONTRIBUTING.md
=> Removed inconsistent format entries as asked in issue no #933 

scripts/hello_world_kirti36.py
=> Created python script for hello world

CONTRIBUTING.md, profiles/Muaaz_Ahmad.md, scripts/hello_world_muaazahmad00.py
=> HacktoberFest-2022 PR-Muaaz

scripts/hello_world_YorLecaros.js
=> Added file hello_world_YorLecaros.js

scripts/hello_new_world/hello.cpp
=> created a hello world cpp file

scripts/hello_world_rishi_mathur.js
=> for hacktoberfest

CONTRIBUTING.md
to add profile of contributor
added my profile
added place, bio and github
=> modified Contribution.md 

CONTRIBUTING.md, profiles/Rjndrkha.md, scripts/hello_world_rjndrkha.py
1. Add Contributing Md
2. Create Profile.md
3. Add Helloworld Code
Please Assign with Hacktoberfest i already star
=> Create Contributing Md,Profile,Code Hello World

CONTRIBUTING.md, profiles/tusharjain01.md, scripts/hello_world_tusharjain01.java
Completed all the three tasks.
=> Contributed to first open source project

CONTRIBUTING.md, scripts/hello-world-bairwa25.js
- Add name to contribution list.
- #1021
-  `1.` CONTRIBUTING.md
-  `2.` Script
=> added bairwa25 profile

CONTRIBUTING.md
=> Added name

cf-C1. Good Subarrays (Easy Version)-solution
cf two pointer solution in CP template
C1. Good Subarrays (Easy Version)
-
-  `1.`
-  `..`
=> Create cf-C1. Good Subarrays (Easy Version)-solution

CONTRIBUTING.md, profiles/shashwat_poudel.md, scripts/hello_world_shashwat-pd.py
=> Shashwat pd

profiles/Harshit_Mehra.md, scripts/Hello_World_HarshitM.py
- Print hello world - import statement
- In the code
- Added the code
=> Hello world - import statement

profiles/Apil.md, scripts/hello_world_apil_acharya.js
=> hactoberfest_2022

CONTRIBUTING.md, profiles/Rizky_Purba_Dharmawan.md, scripts/hello_world_rizkypur.js
=> add name, profile and script

CONTRIBUTING.md
=> Committed changes please add

CONTRIBUTING.md, profiles/Tarun_Mankar.md, scripts/hello_world_tarun.js
added my name to contributing.md file, added my profile and script also
=> added my name 

profiles/Vivek-raj-64.md, scripts/hello_world_Vivek-raj-64.js
=> Added my profile to list of contributors

profiles/Aman_singh.md
=> add a profile page

CONTRIBUTING.md, profiles/IshaSharma.md, scripts/HELLO_WORLD_ishyyyy.c
-  `1.` contributing.md
-  `2.` profile
- `3.` script
=> updated some files

profiles/Arjun_Sethi.md, scripts/HELLO_WORLD_Arjun
=> Added Profile and Script

profiles/deatiny_erhabor.md, scripts/hello_world_Destiny_Erhabor.py
=> Created profile and hello world script

scripts/hello_world_icextreme.rs
- Closes #967
- Add "Hello World!" program in Rust
-  `1.`
-  `..`
=> Add "Hello World!" program in Rust

scripts/hello_world_KayodeOlusi.js
- Create a script to print "Hello World" in any language
- Created a file named "hello_world_KayodeOlusi.js" that prints "Hello World" to the console.
- Added js file to the scripts folder to print "Hello World"
=> created a script to print "Hello world" in js

CONTRIBUTING.md
- Name added to contributers.md
-
-  `1.`
-  `..`
=> name added to contributers.md

CONTRIBUTING.md, profiles/Aarushi.md, scripts/hello_world_aarushiksk.java
=> Hello World Program

CONTRIBUTING.md, profiles/Gaurav.md, scripts/hello_world_grvsh02.py
=> added contribution

CONTRIBUTING.md
- Add my name in contributing.md file
-
-  `1.`Added my username in the contributing.md file
-  `..`
=> Added info to contributing.md

scripts/shell.sh
-write hello world in shell
-
-  `1.`
-  `.. printed hello world
=> Created hello world in shell

CONTRIBUTING.md, profiles/abilsabili50.md
-  `1.` add abilsabili50 into Contributors list and add abilsabili50 profile into profiles directory
=> Add abilsabili50

scripts/hello_world_ZolaraCodes.js
=> Added my Hello World File! Zolars Hello_World.js

scripts/hello_world_subhagata.cpp
thank you for reading my pull request
=> Hello World by Subhagata

scripts/hello_world_kushagra.py
- All script redundant
- Added new script
-  `1.`
-  `..`
=> Added a new script

scripts/hello_world_aishwaryam.cpp
=> Commit hello world message

profiles/Anurag_Shukla.md
- Create Profile
- Created Profile
=> Created Profile

scripts/hello_world_CarissaLi.js
-
-
-  Added hello world script
=> add script

CONTRIBUTING.md
- Update Contributers list.
- Updated Contributers list.
-  `1.` Added name,bio,github info.
-  `..`
=> Added info to Contributers.md file

CONTRIBUTING.md
-Update name contributers list.
-Updated name contributers list.
-  `1.` Added name ,bio and github information.
-  `..`
=> added name to contributers list

scripts/hello_new_world/hello_world_picturepatch07.java
Added hello world code in java
=> code added

CONTRIBUTING.md
-  Update contributing.md
-  Updated contributing.md
-  `1. Added Name, bio, and github profile`
=> Update CONTRIBUTING.md and added Name and Bio

profiles/Yash_Raj_Singh.md
- Add a profile page to the profiles directory
- Added my profile page to the profiles directory
-  `1.` Added a markdown of my profile in the profiles directory.
=> Added myself

profiles/profile (vijay adhikari)
=> Create profile (vijay adhikari)

scripts/harshwalia_hello_world.cpp
-open sourcetion
- contribution
-  `1.`
-  `..`
=> creted a hello world cpp file

edit_distance.cpp
language : CPP
Author : Ramanujam 
github : https://github.com/ramanujam001
- edit distance 
- using CPP and having time complexity O(3^m)
-  `1.`
-  `..`
=> DSA_edit_distance.cpp

CONTRIBUTING.md
-contribution to my first open source
- added my name to the contribution list
-  `1.`
-  `..`
=> added harsh walia to contributuion

Factorial of a number
Please tag it as hacktoberfest
-
-
-  `1.`
-  `..`
=> Create Factorial of a number

CONTRIBUTING.md
Add name in contributing.md
Added
Accept my PR
=> Add name in contributing.md

scripts/calculator.py
- Python program
- Calculator Which will help to add, subtract , Multiply and divide
-  `1.`
-  `..`
=> calculator program using Python

CONTRIBUTING.md, profiles/Ayush_Shukla.md, scripts/helloWorld.py
=> Addded my name and interest

CONTRIBUTING.md, profiles/Mohasin-Haque.md, scripts/networkStatusChecker.js
I have added the script to check your network status, If you are online it will show online else offline. Please check the preview here:- https://techie-tessie.github.io/network-status-checker
=> feat: added script for network status checker

profiles/Rohit_Shaw.md
=> profile of rohit shaw

scripts/hello_world_celsotlpn.js
=> My first open source commit

scripts/hello_world_Trinculo54.js
-  `1.` Added my hello world to the repo
=> Add Trinculo54 hello world

CONTRIBUTING.md
#1023 
added my details  in contribution.md
=> Commit message

CONTRIBUTING.md, README.md, profiles/Rizky_Husain.md, scripts/hello_world_rizkyhusain.js
-
-
-  `1. Modified add my name ==> CONTRIBUTING.md`
-  `2. Add new file my profile page ==> Rizky_Husain.md`
- `3. Add new file hello world ==> hello_world_rizkyhusain.js`
`Thanks to read and merge my pull request`
=> Rizky Husain

scripts/hello_world_VickyRaghuwanshi.py
- Hello World Script in Python
- File Name : hello_world_VickyRaghuwanshi.py
=> Added Hello World Script in python

CONTRIBUTING.md, scripts/HelloWorld_aditya.java
=> profile added

README.md, scripts/Hackerfest.py
=> Add some changes

profiles/Anjali_Verma.md
=> Added Contribution for Hacktoberfest-2022

scripts/HELLO_WORLD_ANJALI.py
=> Added Contribution for Hacktoberfest-2022 in Script

CONTRIBUTING.md
=> Added myself as a contributor

scripts/hello_world_BrandLop.exs
=> Add: elixir script

.gitignore
=> Ignore MS Windows image thumbnail cache

scripts/helloworld.pas
=> Pascal version

scripts/hello_world_somssingh.js
added hello world file to scripts folder
please consider my pull request
=> added hello world file to scripts folder

Shakyan.md
=> Commit changes

scripts/hello_world_ArpitSahu01.dart
- To add file to scripts folder
- Added file
-  `1.`
-  `..`
=> Added hello world to scripts

scripts/hello_world_aman.swift
=> hello_world_aman.swift file added

scripts/hello_world_quanhieu.go
-
-
-  `1. Update script hello_world_quanhieu.go`
-  `..`
=> PR: hello_world by go

scripts/Pow_x,n.cpp
This is the solution to the medium level leetcode problem: https://leetcode.com/problems/powx-n
- Implement [pow(x, n)](http://www.cplusplus.com/reference/valarray/pow/), which calculates x raised to the power n (i.e., xn).
- The code provides the solution to the leetcode problem
-  `1.`
-  `..`
=> Pow_x,n.cpp

scripts/HELLO WORLDDD IN C++
-updation
-added using c++
-  `1.`
-  `..`nothing
=> Create HELLO WORLDDD IN C++

profiles/MasonenDanny.md, scripts/MasonenDanny_hello_world.py
=> Added new person

scripts/hello.idr
Hello World script
Idris
Add hello world in idris
=> Add hello world in idris

profiles/Olga_Moz.md
- choose one of 3 way to contribute
- I have added a new profile page
- new profile page added
Thanks for reading my pull request
Long Live Hacktoberfest :)
=> added a new profile - OMoz - #Hacktoberfest2022

scripts/hello_world_urielglb.exs
-Add a hello world in any language with personal data
-Add an hello world in elixir
=> Add Elixir script

scripts/HelloWorld_Surabhi.ts
-Issue #1332 
-Created a file with Hello World..!! written in typescript.
-  `1.`
-  `..`
=> Created HelloWorld_Surabhi.ts

profiles/lakshitha_samod.md
=> created lakshitha_samod.md

scripts/hello_world_lakshithasamod.js
=> added hello_world script file

scripts/hello_world_hoonn9.ts
=> Add hello_world script in ts

scripts/hello_world_Gyanadipta.Scala, scripts/hello_world_Gyanadipta.r
Hello World Program addition
-
-  `1.`Added hello world programs in Scala 
-  `2`Added hello world programs in R
=> Added hello world programs in Scala and R languages

scripts/hello_world_pws.ps1
- Powershell script was missing
- added ps1 script in script folder
- 
- addition of ps1 script
=> added Powershell hello world script

scripts/helloworldJain.cpp
=> Add contribution

scripts/Hello_World_Ashu2001.py
Added hello world
Added hello world in python under scripts folder.
-  `1.`
-  `..`
=> Added hello world

scripts/HelloWorldPy.py
N/A
Simple python script for printing 'Hello World'
Print() function
Adding my file to contribute for HacktoberFest 2022
=> HacktoberFest 2022 Entry

scripts/HelloWorld_SayakDutta.java
Created a Hello World Program using Java
=> Created a Hello World Program 

CONTRIBUTING.md
=> added to CONTRIBUTING.md

scripts/hello_world_vansh_kela.py
=> added hello_world_vansh_kela.py

scripts/hello_world-sachinpantha.js
=> Added Fibonacci sequence code

CONTRIBUTING.md, scripts/hello_world_skeeler79.js
Hacktoberfest2022
Added profile info and Hello World code
-  `1.`
=> create profile and hello world code

scripts/hello_world_Ayush_Keshwan.py
- Add hello_world.py
- created hello_world_Ayush_Keshwan.py
-  Added hello_world_Ayush_Keshwan.py in the scripts folder
=> Added hello_world_Ayush_Keshwan.py to the scripts folder.

CONTRIBUTING.md, profiles/Avin_madhu.md, scripts/Helloworld.java, scripts/hello_world_avin-madhu.py
profile added
hello world program added
bio added
=> added hello world 

CONTRIBUTING.md, profiles/Soumyadwip_Chanda.md, scripts/hello_world_da-r-k.cpp, scripts/helloworld.java
=> Added hello world in c++

CONTRIBUTING.md, profiles/Dishank_Kumar_Yadav.md, scripts/Helloworld.java, scripts/hello_world_dishankkumaryadav.js
=> Task Completed

CONTRIBUTING.md, profiles/Ashish_Mohite.md
=> added my profile page

python program
=> Create python program

currency converter js/RandeerWithanage.js, currency converter js/css.css, currency converter js/index.html
use java script
- currency converter
- 
-  `1.`
-  `..`
=>  currency converter js

profiles/Bhupender_singh.md
=> added readme file Bhupender Singh

profiles/Abdul_Waheed.md
=> added changes

profiles/Axel_Rammon.md
=> Add me on this repo

scripts/hello_word_FebriTahta.js
-
-
-  `1. hello_word_FebriTahta.js`
-  `..`
=> Add FebriTahta js to scripts

hello program
=> Create hello program

Tower Of Hanoi
=> Tower Of Hanoi Algorithm 

profiles/Syed_Ahmed.md, scripts/HelloWorld.go
=> added hello world script in go

CONTRIBUTING.md, profiles/Aditya_Sharma.md, scripts/hello_world_adityasharma270103.py
This is my second pull request for Hacktoberfest2022 22 October,2022
=> added myself-adityasharma270103

profiles/Arunava Debnath.md
- Add my profile
- Add my profile
=> Add my own profile

CONTRIBUTING.md
=> Update CONTRIBUTING.md by Harmanjot Kaur

CONTRIBUTING.md, profiles/aditya_shukla.md, scripts/hello_world_adityasays.js
- #931 #628 #600 #613 #598 #596
-
-  `1.` Added the script
-  `2.` Added profile.md file
- `3.` Added name in contributors.md
=> added script , profile , contributor name

scripts/Python Program/BMI_Calculator.py
A simple command line BMI calculator is added into a folder called Python Program
- There is no BMI calculator in the project
- I have added a simple commad line BMI calculator in the folder named Python Program 
@fineanmol
=> A simple BMI Calculator is added

profiles/Naymul Islam.md, scripts/hello_world_Naymul_Islam.py
Hello world program of naymul Islam is added
@fineanmol
=> Hello world is added into the scripts folder

profiles/Naymul Islam.md
in the profile section my file mean the profile of Naymul Islam is added
@fineanmol
=> My porfile is added

profiles/Ishan_Dutta.md
=> :memo: Add Profile

CONTRIBUTING.md, profiles/PrashansaParwal.md, scripts/hello_word_Prashansa.js
=> initial  commit

CONTRIBUTING.md, profiles/Sithum_Raveesha.md, scripts/hello_world_sithum20210380.js
Done with initial steps to start colloborating
=> docs : start contributing

profiles/Upendra_Yadav.md
=> Create my profile .md file

CONTRIBUTING.md, profiles/Koduri_Mohan.md, scripts/hello_world_kodurimohan.go
- hactoberfest
- updated CONTRIBUTING.md, added profile and added hello_world script
=> updated CONTRIBUTING.md, added profile and added hello_world script

CONTRIBUTING.md, scripts/hello_world_3mYouOL.emojic
- #2223 
- #931 
-  Add personal profile to `CONTRIBUTING.md`
-  Add `Hello World` script in [Emojicode](https://www.emojicode.org)
=> Add HelloWorld in Emojicode

CONTRIBUTING.md
added my name to contributors list
=> name added

CONTRIBUTING.md, profiles/Vaibhav.md, scripts/Hello_world_Vaibhav.py
-
-  `1.` Added the script
-  `2.` Added profile.md file
-  `3.` Added name in contributors.md file
=> Added script and profile

scripts/hello_world_jerik.js
Created the hello world script file
=> Created hello_world_jerik.js

Python/password_checker.py
A beginner friendly python program for checking passwords and rate them as per their use of valid characters and length.
=> Added a python program to check password for validity and it's strength.

CONTRIBUTING.md
=> Adding NIKIK

CONTRIBUTING.md
Added my details in contributing.md . Can u plz accept it under hactoberfest 2025 tag. Thank you!
=> added my name in contributing

profiles/Bhawana_Sharma.md
- Added a new profile page as per Task 2 instructions.
- Created a Markdown file named **Bhawana_Sharma.md** inside the `profiles` directory.
- The file includes my details such as location, academics, interests, skills, and GitHub profile link.
- `1.` Added **Bhawana_Sharma.md** in the `profiles/` directory.
- `2.` Included personal information in Markdown format for Hacktoberfest 2025 contribution.
- `3.` Ensured the file follows the profile page template structure.
=> Added my profile - Bhawana_Sharma.md

profiles/pavan.md
- tought of adding my profile to the profile folder
-
just simple crreated a file with my name and md extension and apply chnages
-  `1.`
-  `..` added my profile to the profiles folder
=> added profile.md

CONTRIBUTING.md
Added my personal details to CONTRIBUTING.md for Hacktoberfest 2025.
=> Added my name - Nithin S

profiles/nithin_s.md
Added my personal profile page in the profiles folder for Hacktoberfest 2025.
=> Added my profile page - Nithin S

CONTRIBUTING.md, Java/Calculator.java
=> Java Program for Calculator

profiles/Varad_agrawal.md
I have added my profile info . So please merge the PR and labeled this as "hacktober-accepted"
=> Added My Profile Info

scripts/hello_world_varadraj75.js
printing hello world using javascript
=> Added JavaScript file in scripts folder

CONTRIBUTING.md
Did not have my profile details updated!
Added it to CONTRIBUTING.md
-  `1.`Added my name to the CONTRIBUTING.md file.`
-  `2.`Added the location I am from.
-  `3. `Added a short bio.
=> Sourashis Profile Update

scripts/hello_world_anshika.js
=> hello world script

CONTRIBUTING.md
Name: [Dhruvika Rawat](https://github.com/dhruvika11rawat)
Place: Dehradun, Uttarakhand, India
Bio: A 1st year student at IIIT Lucknow pursuing B.Tech in Computer Science and Business.
GitHub: [dhruvika11rawat](https://github.com/dhruvika11rawat)
=> added name in hacktoberfest
